# Generated by Django 3.0.1 on 2020-01-03 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(db_column='ITEM_ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(blank=True, db_column='ITEM_IMAGE', null=True, upload_to='item/image/', verbose_name='IMAGE')),
                ('item_bool', models.BooleanField(blank=True, db_column='ITEM_BOOL', null=True, verbose_name='BOOL')),
                ('item_date', models.DateField(auto_now_add=True, db_column='ITEM_DATE', null=True, verbose_name='DATE')),
                ('item_update_date', models.DateTimeField(auto_now=True, db_column='ITEM_UPDATE_DATE', null=True, verbose_name='UPDATE_DATE')),
                ('item_decimal', models.DecimalField(blank=True, db_column='ITEM_DECIMAL', decimal_places=2, max_digits=5, null=True, verbose_name='DECIMAL')),
                ('item_email', models.EmailField(blank=True, db_column='ITEM_EMAIL', max_length=254, null=True, verbose_name='EMAIL')),
                ('item_file', models.FileField(blank=True, db_column='ITEM_FILE', max_length=254, null=True, upload_to='item/file/', verbose_name='FILE')),
                ('item_integer', models.IntegerField(blank=True, db_column='ITEM_INTEGER', default=1, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)], verbose_name='INTEGER')),
                ('item_slug', models.SlugField(blank=True, db_column='ITEM_SLUG', max_length=60, null=True, verbose_name='SLUG')),
                ('item_name', models.TextField(blank=True, db_column='ITEM_TEXT', null=True, verbose_name='TEXT')),
                ('item_url', models.URLField(blank=True, db_column='ITEM_URL', null=True, verbose_name='URL')),
                ('item_uuid', models.UUIDField(blank=True, db_column='ITEM_UUID', null=True, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'ITEM',
                'ordering': ['item_id'],
                'managed': True,
            },
        ),
    ]
