# Generated by Django 3.0.1 on 2020-01-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_date_auto',
            field=models.DateField(auto_now_add=True, db_column='ITEM_DATE_AUTO', null=True, verbose_name='DATE_AUTO'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_date',
            field=models.DateField(blank=True, db_column='ITEM_DATE', null=True, verbose_name='DATE'),
        ),
    ]
