# Generated by Django 3.0.1 on 2020-01-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodels', '0002_auto_20200106_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_update_date_auto',
            field=models.DateTimeField(auto_now=True, db_column='ITEM_UPDATE_DATE_AUTO', null=True, verbose_name='UPDATE_DATE_AUTO'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_update_date',
            field=models.DateTimeField(blank=True, db_column='ITEM_UPDATE_DATE', null=True, verbose_name='UPDATE_DATE'),
        ),
    ]
