# Generated by Django 2.2.6 on 2019-12-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(db_column='COLOR_ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(blank=True, db_column='COLOR_NAME', max_length=20, null=True, unique=True, verbose_name='NAME')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'COLOR',
                'ordering': ['color_id'],
                'managed': True,
            },
        ),
    ]
