# Generated by Django 3.0 on 2019-12-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(blank=True, db_column='COLOR_NAME', max_length=20, null=True, unique=True, verbose_name='NAME'),
        ),
    ]
