# Generated by Django 3.0.1 on 2020-01-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestReact',
            fields=[
                ('test_react_id', models.AutoField(db_column='TEST_REACT_ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('test_react_description', models.CharField(blank=True, db_column='TEST_REACT_DESCRIPTION', max_length=200, null=True, verbose_name='DESCRIPTION')),
                ('test_react_title', models.CharField(blank=True, db_column='TEST_REACT_TITLE', max_length=200, null=True, verbose_name='TITLE')),
            ],
        ),
    ]
