# Generated by Django 3.0.1 on 2020-01-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreact',
            name='test_react_description',
            field=models.CharField(blank=True, db_column='TEST_REACT_DESCRIPTION', max_length=500, null=True, verbose_name='DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='testreact',
            name='test_react_title',
            field=models.CharField(blank=True, db_column='TEST_REACT_TITLE', max_length=100, null=True, verbose_name='TITLE'),
        ),
    ]
