# Generated by Django 3.0.1 on 2020-01-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_1', '0002_auto_20200116_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreact',
            name='test_react_image',
            field=models.ImageField(blank=True, db_column='TEST_REACT_IMAGE', null=True, upload_to='react_1/image/', verbose_name='IMAGE'),
        ),
    ]
