# Generated by Django 3.0.1 on 2020-01-21 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angular_2', '0002_mix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mix',
            options={'managed': True, 'verbose_name': 'Mix.', 'verbose_name_plural': 'Mixs.'},
        ),
        migrations.AlterUniqueTogether(
            name='mix',
            unique_together={('testing_id', 'images_id')},
        ),
        migrations.AlterModelTable(
            name='mix',
            table='MIX',
        ),
    ]
